spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://127.0.0.1:3306/blog?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  thymeleaf:
#    encoding: UTF-8
#    cache: false
#    mode: HTML5
elasticsearch:
  ip: 127.0.0.1
  port: 9300
  pool: 5
  cluster:
    name: es-app1